const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const admin=fs.readFileSync(path.join(__dirname,'../public/admin/index.html'),'utf8');
const script=fs.readFileSync(path.join(__dirname,'../public/admin/ladder.js'),'utf8');
test('AI media owns the three content actions, while settings retains only ranking generation',async()=>{
  const content={},status={};
  const context={document:{getElementById:id=>id==='content'?content:status},api:async()=>({ranking:{tradeDate:'2026-10-09'}})};
  vm.runInNewContext(script,context);context.renderAiMedia();await Promise.resolve();
  assert.match(content.innerHTML,/模板来自抖音连扳炒家/);
  assert.match(content.innerHTML,/switchView\('ladder'\)/);
  assert.match(content.innerHTML,/switchView\('dragon'\)/);
  assert.match(content.innerHTML,/generateRankingCopy\(this\)/);
  assert.match(content.innerHTML,/generateRankingPoster\('inflow',this\)/);
  assert.match(content.innerHTML,/generateRankingPoster\('outflow',this\)/);
  assert.match(status.textContent,/2026-10-09/);
  assert.doesNotMatch(admin,/onclick="generateRanking(Copy|Poster)/);
  assert.match(admin,/onclick="generateDarkFundRanking\(\)"/);
  assert.match(admin,/data-view="aiMedia"/);
  assert.doesNotMatch(admin,/data-view="ladder"/);
});
test('ladder subpage keeps the AI media menu selected',()=>{
  let selected=false,rendered=false;
  const title={};
  const context={document:{querySelectorAll:()=>[{dataset:{view:'aiMedia'},classList:{toggle:(name,value)=>{selected=value;}}}],getElementById:()=>title},TITLES:{ladder:'AI自媒体 / 连板天梯图生成'},renderLadder:()=>{rendered=true;}};
  vm.runInNewContext(admin.match(/function switchView\(v\) \{[\s\S]*?\n\}/)[0],context);
  context.switchView('ladder');assert(selected);assert(rendered);assert.match(title.textContent,/AI自媒体/);
  rendered=false;context.TITLES.dragon='AI自媒体 / 游资龙虎榜图生成';
  context.switchView('dragon');assert(selected);assert(rendered);assert.match(title.textContent,/游资龙虎榜/);
});
